module.exports = {
  "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "username",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/auth/account",
    "failureRedirect": "/local",
    "failureFlash": true,
    "setAccessToken" : true,
    "session" : true,
    "forceDefaultCallback" : true
  },
  "facebook-login": {
    "provider": "facebook",
    "module": "passport-facebook",
    "clientID": process.env.FACEBOOK_LOGIN_CLIENT_ID,
    "clientSecret": process.env.FACEBOOK_LOGIN_CLIENT_SECRET,
    "callbackURL": "/auth/facebook/callback",
    "authPath": "/auth/facebook",
    "callbackPath": "/auth/facebook/callback/",
    "successRedirect": "/api/MyUsers/authenticated",
    "failureRedirect": "/login",
    "scope": ["email", "public_profile"],
    "failureFlash": true
  },
  "google-login": {
    "provider": "google",
    "module": "passport-google-oauth",
    "strategy": "OAuth2Strategy",
    "clientID": process.env.GOOGLE_LOGIN_CLIENT_ID,
    "clientSecret": process.env.GOOGLE_LOGIN_CLIENT_SECRET,
    "callbackURL": "/auth/google/callback",
    "authPath": "/auth/google",
    "callbackPath": "/auth/google/callback/",
    "successRedirect": "/api/MyUsers/authenticated",
    "failureRedirect": "/api/MyUsers/authentication/failed",
    "scope": ["email", "profile"],
    "failureFlash": true
  },
  "twitter-login": {
    "provider": "twitter",
    "authScheme": "oauth",
    "module": "passport-twitter",
    "callbackURL": "/auth/twitter/callback",
    "authPath": "/auth/twitter",
    "callbackPath": "/auth/twitter/callback",
    "successRedirect": "/api/MyUsers/authenticated",
    "failureRedirect": "/login",
    "consumerKey": process.env.TWITTER_LOGIN_CONSUMER_KEY,
    "consumerSecret": process.env.TWITTER_LOGIN_CONSUMER_SECRET,
    "failureFlash": true
  },
  "facebook-link": {
    "provider": "facebook",
    "module": "passport-facebook",
    "clientID": process.env.FACEBOOK_LOGIN_CLIENT_ID,
    "clientSecret": process.env.FACEBOOK_LOGIN_CLIENT_SECRET,
    "callbackURL": "/link/facebook/callback",
    "authPath": "/link/facebook",
    "callbackPath": "/link/facebook/callback",
    "successRedirect": "/api/MyUsers/authenticated",
    "failureRedirect": "/login",
    "scope": ["email", "user_likes"],
    "link": true,
    "failureFlash": true
  },
  "google-link": {
    "provider": "google",
    "module": "passport-google-oauth",
    "strategy": "OAuth2Strategy",
    "clientID": process.env.GOOGLE_LOGIN_CLIENT_ID,
    "clientSecret": process.env.GOOGLE_LOGIN_CLIENT_SECRET,
    "callbackURL": "/link/google/callback",
    "authPath": "/link/google",
    "callbackPath": "/link/google/callback/",
    "successRedirect": "/api/MyUsers/authenticated",
    "failureRedirect": "/login",
    "scope": ["email", "profile"],
    "link": true,
    "failureFlash": true
  }
};
